### ISSUE TITLE
Failed to build: optitrack_broadcast/Mocap.h: No such file or directory

### ISSUE THREAD

**Issue by Norton-z** [LonghaoQian/optitrack_broadcast#2]
Thanks for your share very much! @LonghaoQian  
When i build the code, it reports the error: "optitrack_broadcast/Mocap.h: No such file or directory", how can i get this Mocap.h file? 
Thanks！

**Comment by LonghaoQian** [comment]
This file is auto generated by

```
 add_message_files(
   DIRECTORY msg # telling the location of the custom message
   FILES
   Mocap.msg
)
```

the Mocap.msg is in _msg_ folder.

Did you use catkin_build to build the ros node?

**Comment by Norton-z** [comment]
Thanks!  I use catkin build to build it again. It's successful!
